import type { ICaseCopilotProvider } from '../../../../domain/ai/services';
import type { CaseContext } from '../../../../domain/ai/CaseContext';
import type { CaseCopilotEmailDraft, CaseCopilotInsights, CaseCopilotMessage } from '../../../../domain/ai/CaseCopilot';
import { serializeContextForPrompt } from '../../../../application/ai/caseKnowledgeService';
import { getCaseChatPrompt, getCaseEmailPrompt, getCaseInsightsPrompt } from '../../prompts/caseCopilotPromptLibrary';
import { loadAISettings } from '../../settings/aiSettingsStorage';
import {
  estimateGeminiCostUsd,
  estimateTokens,
  recordUsage,
  updateProviderHealth,
  getProviderHealth,
} from '../../telemetry/aiUsageTelemetry';
import { callGeminiGenerate, GeminiApiError } from './geminiApiClient';
import { parseCaseCopilotInsights, parseEmailDraft } from './caseCopilotResponseParser';
import { GeminiResponseParseError } from './geminiResponseParser';
import { generateHeuristicInsights } from '../../copilot/caseCopilotHeuristics';

export class GeminiCaseCopilotProvider implements ICaseCopilotProvider {
  readonly id = 'gemini';
  readonly name = 'Google Gemini Case Copilot';

  isConfigured(): boolean {
    const settings = loadAISettings();
    if (!settings.geminiEnabled) return false;
    const health = getProviderHealth(this.id);
    if (health && !health.configured) return false;
    return true;
  }

  private async generate(prompt: string): Promise<{ text: string; latencyMs: number }> {
    const settings = loadAISettings();
    const result = await callGeminiGenerate(prompt, settings.geminiModel);
    const usage = {
      providerId: this.id,
      model: settings.geminiModel,
      requestChars: prompt.length,
      estimatedInputTokens: result.estimatedInputTokens || estimateTokens(prompt),
      estimatedOutputTokens: result.estimatedOutputTokens || estimateTokens(result.text),
      estimatedCostUsd: estimateGeminiCostUsd(
        result.estimatedInputTokens || estimateTokens(prompt),
        result.estimatedOutputTokens || estimateTokens(result.text),
        settings.geminiModel,
      ),
      latencyMs: result.latencyMs,
      timestamp: new Date().toISOString(),
    };
    recordUsage(usage);
    updateProviderHealth({
      providerId: this.id,
      configured: true,
      enabled: true,
      lastSuccessfulCall: usage.timestamp,
      lastLatencyMs: usage.latencyMs,
    });
    return { text: result.text, latencyMs: result.latencyMs };
  }

  async generateInsights(context: CaseContext): Promise<CaseCopilotInsights> {
    const contextJson = serializeContextForPrompt(context);
    const { prompt } = getCaseInsightsPrompt(contextJson);
    try {
      const { text } = await this.generate(prompt);
      return parseCaseCopilotInsights(text, context, this.id);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Gemini insights failed';
      updateProviderHealth({ providerId: this.id, lastError: message });
      const fallback = generateHeuristicInsights(context);
      return { ...fallback, executiveSummary: `${fallback.executiveSummary} (AI unavailable: ${message})` };
    }
  }

  async askQuestion(context: CaseContext, question: string, history: CaseCopilotMessage[]): Promise<string> {
    const contextJson = serializeContextForPrompt(context);
    const historyText = history.slice(-10).map((m) => `${m.role}: ${m.content}`).join('\n');
    const { prompt } = getCaseChatPrompt(contextJson, question, historyText);
    try {
      const { text } = await this.generate(prompt);
      return text.trim();
    } catch (err) {
      return err instanceof GeminiApiError || err instanceof GeminiResponseParseError
        ? `Unable to answer right now: ${err.message}`
        : 'Unable to answer right now. Please try again.';
    }
  }

  async generateEmailDraft(
    context: CaseContext,
    type: CaseCopilotEmailDraft['type'],
  ): Promise<{ subject: string; body: string }> {
    const contextJson = serializeContextForPrompt(context);
    const { prompt } = getCaseEmailPrompt(contextJson, type);
    try {
      const { text } = await this.generate(prompt);
      return parseEmailDraft(text);
    } catch {
      return {
        subject: `Regarding your immigration case — ${context.client.name}`,
        body: `Dear ${context.client.name},\n\n[Draft could not be generated by AI. Please compose manually.]\n\nBest regards,\nYour Immigration Team`,
      };
    }
  }
}

export const geminiCaseCopilotProvider = new GeminiCaseCopilotProvider();
